spring:
  application:
  name:
    wire
  jpa:
    hibernate:
      ddl-auto:
        create-drop
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect.MySQL8Dialect
        format_sql:
          true
    show-sql:
        true
    defer-datasource-initialization:
      true

datasource:
  url: jdbc:mysql://mysql:3306/test
  username: user
  password: 1234
  driver-class-name: com.mysql.cj.jdbc.Driver
  initialization-mode:
    always
